-- Sounditem definitions. same format as gamedata/sounds.lua 
-- these are templates used by the editor. for the table of sound items being used by emitters, see ambient_sounds_instances.lua

local Sounds = {
	Sounditems = {
		["$center$ wind_mighty_3"] = {
			delay = 1,
			dopplerscale = 0,
			emitter = false,
			file = "maps/white_rabbit_v30.sdd/Sounds/Ambient/wind_mighty_3.ogg",
			gain = 1,
			gainMod = 0.050000000745058,
			in3d = true,
			length_loop = 1,
			length_real = 0,
			maxconcurrent = 2,
			maxdist = 1000000,
			pitch = 1,
			pitchMod = 0,
			preload = true,
			priority = 0,
			rnd = 0,
			rolloff = 0,
			template = "wind_mighty_3",
		},
		["$test$ brook_1"] = {
			file = "maps/white_rabbit_v30.sdd/Sounds/Ambient/brook_1.ogg",
			template = "brook_1",
		},
		["$test$ brook_2"] = {
			delay = 1,
			dopplerscale = 0,
			emitter = false,
			file = "maps/white_rabbit_v30.sdd/Sounds/Ambient/brook_2.ogg",
			gain = 1,
			gainMod = 0.050000000745058,
			in3d = true,
			length_loop = 1,
			length_real = 20,
			maxconcurrent = 2,
			maxdist = 1000000,
			pitch = 1,
			pitchMod = 0,
			preload = true,
			priority = 0,
			rnd = 0,
			rolloff = 0,
			template = "brook_2",
		},
		["$test$ brook_4"] = {
			delay = 1,
			dopplerscale = 0,
			emitter = false,
			file = "maps/white_rabbit_v30.sdd/Sounds/Ambient/brook_4.ogg",
			gain = 1,
			gainMod = 0.050000000745058,
			in3d = true,
			length_loop = 1,
			length_real = 60,
			maxconcurrent = 2,
			maxdist = 1000000,
			pitch = 1,
			pitchMod = 0,
			preload = true,
			priority = 0,
			rnd = 0,
			rolloff = 0,
			template = "brook_4",
		},
	},
}
return Sounds