-- Sounditem definitions. same format as gamedata/sounds.lua 
-- these are templates used by the editor. for the table of sound items being used by emitters, see ambient_sounds_instances.lua

local Sounds = {
	Sounditems = {
		["$center$ owls_3_mono"] = {
			delay = 1,
			dopplerscale = 0,
			emitter = false,
			file = "maps/white_rabbit_v30.sdd/Sounds/Ambient/owls_3_mono.ogg",
			gain = 3,
			gainMod = 0.050000000745058,
			in3d = true,
			length_loop = 1,
			length_real = 300,
			maxconcurrent = 2,
			maxdist = 1000000,
			pitch = 1,
			pitchMod = 0,
			preload = true,
			priority = 0,
			rnd = 0,
			rolloff = 10,
			template = "owls_3_mono",
		},
		["$center$ wind_mighty_2"] = {
			delay = 1,
			dopplerscale = 0,
			emitter = false,
			file = "maps/white_rabbit_v30.sdd/Sounds/Ambient/wind_mighty_2.ogg",
			gain = 1,
			gainMod = 0.050000000745058,
			in3d = true,
			length_loop = 1,
			length_real = 180,
			maxconcurrent = 2,
			maxdist = 1000000,
			pitch = 1,
			pitchMod = 0,
			preload = true,
			priority = 0,
			rnd = 0,
			rolloff = 0.5,
			template = "wind_mighty_2",
		},
		["$ne1$ nightingale_1_mono"] = {
			delay = 1,
			dopplerscale = 0,
			emitter = false,
			file = "maps/white_rabbit_v30.sdd/Sounds/Ambient/nightingale_1_mono.ogg",
			gain = 1,
			gainMod = 0.050000000745058,
			in3d = true,
			length_loop = 1,
			length_real = 180,
			maxconcurrent = 2,
			maxdist = 1000000,
			pitch = 1,
			pitchMod = 0,
			preload = true,
			priority = 0,
			rnd = 0,
			rolloff = 0.20000000298023,
			template = "nightingale_1_mono",
		},
		["$rn1$ brook_2"] = {
			delay = 1,
			dopplerscale = 0,
			emitter = false,
			file = "maps/white_rabbit_v30.sdd/Sounds/Ambient/brook_2.ogg",
			gain = 2,
			gainMod = 0.050000000745058,
			in3d = true,
			length_loop = 28,
			length_real = 28,
			maxconcurrent = 2,
			maxdist = 1000000,
			pitch = 1,
			pitchMod = 0,
			preload = true,
			priority = 0,
			rnd = 1,
			rolloff = 0.25,
			template = "brook_2",
		},
		["$sw3$ woodpigeon_mono"] = {
			delay = 1,
			dopplerscale = 0,
			emitter = false,
			file = "maps/white_rabbit_v30.sdd/Sounds/Ambient/woodpigeon_mono.ogg",
			gain = 2,
			gainMod = 0.050000000745058,
			in3d = true,
			length_loop = 1,
			length_real = 60,
			maxconcurrent = 2,
			maxdist = 1000000,
			pitch = 1,
			pitchMod = 0,
			preload = true,
			priority = 0,
			rnd = 0,
			rolloff = 0.5,
			template = "woodpigeon_mono",
		},
	},
}
return Sounds